set -g mode-keys vi
set -g window-size largest
set -g mouse on
bind-key S-Left swap-window -t -1
bind-key S-Right swap-window -t +1
set-option -g window-size smallest

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

